import { base44 } from '@/api/base44Client';
import { format } from 'date-fns';

const SEVERITY_COLORS = {
  critical: '#dc2626',
  high: '#ea580c',
  medium: '#ca8a04',
  low: '#6b7280',
};

const PRIORITY_COLORS = {
  high: '#dc2626',
  medium: '#ca8a04',
  low: '#16a34a',
};

const ROLE_ACCENT_COLORS = [
  '#6366f1', '#0ea5e9', '#10b981', '#f59e0b',
  '#ef4444', '#8b5cf6', '#06b6d4', '#84cc16',
];

function escapeHtml(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function badge(text, color) {
  return `<span style="display:inline-block;padding:2px 10px;border-radius:999px;font-size:11px;font-weight:600;background:${color}22;color:${color};border:1px solid ${color}44;">${escapeHtml(text)}</span>`;
}

function pageBreak() {
  return `<div style="page-break-before:always;"></div>`;
}

function footer(title, date) {
  return `
    <div class="pdf-footer">
      Generated by TeamSync &nbsp;·&nbsp; ${escapeHtml(title)} &nbsp;·&nbsp; ${escapeHtml(date)}
    </div>
  `;
}

function coverPage(sim, dateStr) {
  const roles = (sim.selected_roles || []).map((r, i) => {
    const color = ROLE_ACCENT_COLORS[i % ROLE_ACCENT_COLORS.length];
    const name = r.role.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
    return `<span style="display:inline-flex;align-items:center;gap:4px;padding:4px 12px;border-radius:999px;font-size:12px;font-weight:500;background:${color}18;color:${color};border:1px solid ${color}33;margin:3px;">
      ${escapeHtml(name)} <span style="font-size:10px;opacity:0.7;">· ${r.influence}/10</span>
    </span>`;
  }).join('');

  return `
    <div class="pdf-page cover-page">
      <div style="flex:1;display:flex;flex-direction:column;justify-content:center;">
        <div style="margin-bottom:12px;">
          ${badge(sim.use_case_type?.replace(/_/g, ' ').toUpperCase() || 'CUSTOM', '#6366f1')}
          &nbsp;
          ${badge('COMPLETED', '#16a34a')}
        </div>
        <h1 style="font-size:36px;font-weight:800;color:#0f172a;line-height:1.2;margin:0 0 8px 0;">${escapeHtml(sim.title)}</h1>
        <p style="font-size:14px;color:#64748b;margin:0 0 32px 0;">Run on ${escapeHtml(dateStr)}</p>

        <div style="margin-bottom:32px;">
          <p style="font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#94a3b8;font-weight:600;margin:0 0 10px 0;">Participating Roles</p>
          <div style="display:flex;flex-wrap:wrap;gap:4px;">${roles}</div>
        </div>

        <div style="background:#f8fafc;border-left:4px solid #6366f1;padding:20px 24px;border-radius:0 8px 8px 0;">
          <p style="font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#94a3b8;font-weight:600;margin:0 0 10px 0;">Scenario</p>
          <p style="font-size:14px;line-height:1.7;color:#334155;margin:0;white-space:pre-wrap;">${escapeHtml(sim.scenario)}</p>
        </div>
      </div>
      ${footer(sim.title, dateStr)}
    </div>
  `;
}

function roleResponsesPage(sim, dateStr) {
  const responses = (sim.responses || []);
  if (!responses.length) return '';

  const cards = responses.map((r, i) => {
    const color = ROLE_ACCENT_COLORS[i % ROLE_ACCENT_COLORS.length];
    const concerns = (r.concerns || []).map(c => `<li style="margin-bottom:4px;">${escapeHtml(c)}</li>`).join('');
    const tensions = (r.predicted_tensions_with || []).map(t =>
      `<span style="display:inline-block;padding:2px 8px;border-radius:4px;font-size:10px;background:#fef3c7;color:#92400e;border:1px solid #fde68a;margin:2px;">${escapeHtml(t)}</span>`
    ).join('');

    return `
      <div style="border-left:4px solid ${color};padding:16px 20px;margin-bottom:20px;background:#fff;border-radius:0 8px 8px 0;box-shadow:0 1px 3px rgba(0,0,0,.06);">
        <div style="display:flex;align-items:center;gap:10px;margin-bottom:12px;">
          <span style="font-size:15px;font-weight:700;color:#0f172a;">${escapeHtml(r.role)}</span>
          ${r.risk_tolerance ? `<span style="font-size:10px;padding:2px 8px;border-radius:4px;background:#f1f5f9;color:#64748b;">${escapeHtml(r.risk_tolerance)} risk</span>` : ''}
        </div>

        ${r.position ? `<p style="font-size:13px;font-weight:600;color:#1e293b;margin:0 0 12px 0;">${escapeHtml(r.position)}</p>` : ''}

        ${concerns ? `
          <div style="margin-bottom:12px;">
            <p style="font-size:10px;text-transform:uppercase;letter-spacing:.07em;color:#94a3b8;font-weight:600;margin:0 0 6px 0;">Concerns</p>
            <ul style="margin:0;padding-left:16px;font-size:12px;color:#475569;line-height:1.6;">${concerns}</ul>
          </div>` : ''}

        ${r.recommendation ? `
          <div style="margin-bottom:12px;">
            <p style="font-size:10px;text-transform:uppercase;letter-spacing:.07em;color:#94a3b8;font-weight:600;margin:0 0 6px 0;">Recommendation</p>
            <p style="font-size:12px;color:#334155;font-style:italic;margin:0;">${escapeHtml(r.recommendation)}</p>
          </div>` : ''}

        ${r.primary_driver ? `<p style="font-size:10px;color:#94a3b8;margin:0 0 10px 0;">Primary driver: <strong style="color:#64748b;">${escapeHtml(r.primary_driver)}</strong></p>` : ''}

        ${r.authentic_voice_quote ? `
          <div style="margin:12px 0;padding:12px 16px;background:#f0fdf4;border-left:3px solid #22c55e;border-radius:0 6px 6px 0;">
            <p style="font-size:12px;font-style:italic;color:#166534;margin:0;">"${escapeHtml(r.authentic_voice_quote)}"</p>
          </div>` : ''}

        ${tensions ? `<div style="margin-top:8px;">${tensions}</div>` : ''}
      </div>
    `;
  }).join('');

  return `
    ${pageBreak()}
    <div class="pdf-page">
      <h2 class="section-title">Role Responses</h2>
      ${cards}
      ${footer(sim.title, dateStr)}
    </div>
  `;
}

function tensionsPage(sim, dateStr) {
  const severityOrder = { critical: 0, high: 1, medium: 2, low: 3 };
  const tensions = [...(sim.tensions || [])].sort((a, b) =>
    (severityOrder[a.severity] ?? 4) - (severityOrder[b.severity] ?? 4)
  );
  if (!tensions.length) return '';

  const cards = tensions.map(t => {
    const color = SEVERITY_COLORS[t.severity] || '#6b7280';
    const roles = (t.between || []).join(' ↔ ');
    return `
      <div style="border:1px solid #e2e8f0;border-radius:8px;padding:16px 20px;margin-bottom:14px;background:#fff;">
        <div style="display:flex;align-items:center;gap:10px;margin-bottom:10px;">
          ${badge(t.severity?.toUpperCase() || 'UNKNOWN', color)}
          <span style="font-size:13px;font-weight:600;color:#334155;">${escapeHtml(roles)}</span>
        </div>
        <p style="font-size:13px;color:#475569;margin:0 0 10px 0;">${escapeHtml(t.description)}</p>
        ${t.root_cause ? `<p style="font-size:11px;color:#64748b;margin:0 0 8px 0;"><strong>Root cause:</strong> ${escapeHtml(t.root_cause)}</p>` : ''}
        ${t.hidden_alignment ? `<p style="font-size:11px;color:#15803d;margin:0;padding:8px 12px;background:#f0fdf4;border-radius:6px;"><strong>Hidden alignment:</strong> ${escapeHtml(t.hidden_alignment)}</p>` : ''}
      </div>
    `;
  }).join('');

  return `
    ${pageBreak()}
    <div class="pdf-page">
      <h2 class="section-title">Tensions</h2>
      ${cards}
      ${footer(sim.title, dateStr)}
    </div>
  `;
}

function synthesisPage(sim, dateStr) {
  const tradeoffs = (sim.decision_trade_offs || []).map(t => `
    <div style="display:grid;grid-template-columns:1fr auto 1fr;gap:10px;align-items:start;margin-bottom:12px;">
      <div style="padding:12px;background:#eff6ff;border-radius:6px;">
        <p style="font-size:10px;font-weight:700;color:#1d4ed8;text-transform:uppercase;margin:0 0 4px 0;">Option A</p>
        <p style="font-size:12px;color:#1e3a8a;margin:0;">${escapeHtml(t.option_a)}</p>
      </div>
      <div style="padding-top:16px;font-size:11px;font-weight:700;color:#94a3b8;text-align:center;">vs</div>
      <div style="padding:12px;background:#fef9f0;border-radius:6px;">
        <p style="font-size:10px;font-weight:700;color:#c2410c;text-transform:uppercase;margin:0 0 4px 0;">Option B</p>
        <p style="font-size:12px;color:#7c2d12;margin:0;">${escapeHtml(t.option_b)}</p>
      </div>
    </div>
    ${t.trade_off ? `<p style="font-size:11px;color:#94a3b8;text-align:center;margin:0 0 16px 0;">${escapeHtml(t.trade_off)}</p>` : ''}
  `).join('');

  const nextStepsRows = (sim.next_steps || []).map((s, i) => {
    const pColor = PRIORITY_COLORS[s.priority] || '#6b7280';
    return `
      <tr style="border-bottom:1px solid #f1f5f9;">
        <td style="padding:8px 10px;font-size:12px;color:#1e293b;width:40%;">${i + 1}. ${escapeHtml(s.action)}</td>
        <td style="padding:8px 10px;font-size:11px;color:#64748b;">${escapeHtml(s.owner_role?.replace(/_/g, ' '))}</td>
        <td style="padding:8px 10px;text-align:center;">${badge(s.priority?.toUpperCase() || '—', pColor)}</td>
        <td style="padding:8px 10px;font-size:11px;color:#64748b;text-align:center;">${s.confidence != null ? s.confidence + '%' : '—'}</td>
        <td style="padding:8px 10px;font-size:11px;color:#64748b;text-align:center;">${s.estimated_hours != null ? s.estimated_hours + 'h' : '—'}</td>
      </tr>
    `;
  }).join('');

  return `
    ${pageBreak()}
    <div class="pdf-page">
      <h2 class="section-title">Decision Synthesis</h2>

      ${sim.summary ? `
        <div style="margin-bottom:24px;">
          <p style="font-size:11px;text-transform:uppercase;letter-spacing:.07em;color:#94a3b8;font-weight:600;margin:0 0 8px 0;">Summary</p>
          <p style="font-size:13px;color:#334155;line-height:1.7;margin:0;white-space:pre-wrap;">${escapeHtml(sim.summary)}</p>
        </div>` : ''}

      ${tradeoffs ? `
        <div style="margin-bottom:24px;">
          <p style="font-size:11px;text-transform:uppercase;letter-spacing:.07em;color:#94a3b8;font-weight:600;margin:0 0 12px 0;">Decision Trade-offs</p>
          ${tradeoffs}
        </div>` : ''}

      ${nextStepsRows ? `
        <div>
          <p style="font-size:11px;text-transform:uppercase;letter-spacing:.07em;color:#94a3b8;font-weight:600;margin:0 0 10px 0;">Next Steps</p>
          <table style="width:100%;border-collapse:collapse;font-family:inherit;">
            <thead>
              <tr style="background:#f8fafc;border-bottom:2px solid #e2e8f0;">
                <th style="padding:8px 10px;font-size:10px;font-weight:700;text-transform:uppercase;color:#94a3b8;text-align:left;">Action</th>
                <th style="padding:8px 10px;font-size:10px;font-weight:700;text-transform:uppercase;color:#94a3b8;text-align:left;">Owner</th>
                <th style="padding:8px 10px;font-size:10px;font-weight:700;text-transform:uppercase;color:#94a3b8;text-align:center;">Priority</th>
                <th style="padding:8px 10px;font-size:10px;font-weight:700;text-transform:uppercase;color:#94a3b8;text-align:center;">Confidence</th>
                <th style="padding:8px 10px;font-size:10px;font-weight:700;text-transform:uppercase;color:#94a3b8;text-align:center;">Est. Hours</th>
              </tr>
            </thead>
            <tbody>${nextStepsRows}</tbody>
          </table>
        </div>` : ''}

      ${footer(sim.title, dateStr)}
    </div>
  `;
}

function outcomePage(outcome, sim, dateStr) {
  if (!outcome) return '';

  const OUTCOME_COLORS = {
    success: '#16a34a',
    partial_success: '#ca8a04',
    failure: '#dc2626',
    abandoned: '#6b7280',
    ongoing: '#6366f1',
  };
  const oColor = OUTCOME_COLORS[outcome.actual_outcome] || '#6b7280';

  const unexpectedIssues = (outcome.unexpected_issues || []).map(u =>
    `<li style="margin-bottom:4px;">${escapeHtml(u)}</li>`
  ).join('');

  const accuracy = outcome.predicted_tensions_accuracy;

  return `
    ${pageBreak()}
    <div class="pdf-page">
      <h2 class="section-title">Outcome</h2>

      <div style="margin-bottom:20px;">
        ${badge(outcome.actual_outcome?.replace(/_/g, ' ').toUpperCase() || 'UNKNOWN', oColor)}
      </div>

      ${accuracy != null ? `
        <div style="margin-bottom:20px;">
          <p style="font-size:11px;text-transform:uppercase;letter-spacing:.07em;color:#94a3b8;font-weight:600;margin:0 0 6px 0;">Tension Prediction Accuracy</p>
          <div style="background:#f1f5f9;border-radius:999px;height:10px;overflow:hidden;">
            <div style="background:${oColor};height:100%;width:${accuracy}%;border-radius:999px;"></div>
          </div>
          <p style="font-size:11px;color:#64748b;margin:4px 0 0 0;">${accuracy}%</p>
        </div>` : ''}

      ${outcome.outcome_notes ? `
        <div style="margin-bottom:20px;">
          <p style="font-size:11px;text-transform:uppercase;letter-spacing:.07em;color:#94a3b8;font-weight:600;margin:0 0 8px 0;">Outcome Notes</p>
          <p style="font-size:13px;color:#334155;line-height:1.7;margin:0;">${escapeHtml(outcome.outcome_notes)}</p>
        </div>` : ''}

      ${unexpectedIssues ? `
        <div style="margin-bottom:20px;">
          <p style="font-size:11px;text-transform:uppercase;letter-spacing:.07em;color:#94a3b8;font-weight:600;margin:0 0 8px 0;">Unexpected Issues</p>
          <ul style="margin:0;padding-left:16px;font-size:12px;color:#475569;line-height:1.6;">${unexpectedIssues}</ul>
        </div>` : ''}

      ${outcome.lessons_learned ? `
        <div style="background:#f8fafc;border-left:4px solid #6366f1;padding:16px 20px;border-radius:0 8px 8px 0;">
          <p style="font-size:11px;text-transform:uppercase;letter-spacing:.07em;color:#94a3b8;font-weight:600;margin:0 0 8px 0;">Lessons Learned</p>
          <p style="font-size:13px;color:#334155;line-height:1.7;margin:0;">${escapeHtml(outcome.lessons_learned)}</p>
        </div>` : ''}

      ${footer(sim.title, dateStr)}
    </div>
  `;
}

export async function exportSimulationPDF(simulation) {
  // Fetch outcome if one exists
  let outcome = null;
  try {
    const outcomes = await base44.entities.SimulationOutcome.filter({ simulation_id: simulation.id });
    outcome = outcomes?.[0] || null;
  } catch (e) {
    // No outcome, skip page
  }

  const dateStr = format(new Date(simulation.created_date || Date.now()), 'yyyy-MM-dd');
  const safeTitle = (simulation.title || 'simulation').replace(/[^a-z0-9]/gi, '-').toLowerCase();
  const filename = `${safeTitle}-teamsync-${dateStr}.pdf`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${escapeHtml(simulation.title)} — TeamSync</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
      background: #fff;
      color: #1e293b;
      font-size: 14px;
      line-height: 1.5;
    }
    .pdf-page {
      width: 100%;
      min-height: 100vh;
      padding: 56px 64px 80px;
      display: flex;
      flex-direction: column;
      position: relative;
    }
    .cover-page {
      padding-top: 80px;
    }
    .section-title {
      font-size: 22px;
      font-weight: 800;
      color: #0f172a;
      margin-bottom: 24px;
      padding-bottom: 12px;
      border-bottom: 2px solid #e2e8f0;
    }
    .pdf-footer {
      position: absolute;
      bottom: 24px;
      left: 64px;
      right: 64px;
      font-size: 10px;
      color: #94a3b8;
      border-top: 1px solid #f1f5f9;
      padding-top: 8px;
      text-align: center;
    }
    @media print {
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      .pdf-page { page-break-after: always; min-height: unset; padding-bottom: 80px; }
      .pdf-page:last-child { page-break-after: avoid; }
      @page { margin: 0; size: A4; }
    }
  </style>
</head>
<body>
  ${coverPage(simulation, dateStr)}
  ${roleResponsesPage(simulation, dateStr)}
  ${tensionsPage(simulation, dateStr)}
  ${synthesisPage(simulation, dateStr)}
  ${outcomePage(outcome, simulation, dateStr)}
  <script>
    document.title = ${JSON.stringify(filename)};
    window.onload = function() {
      setTimeout(function() { window.print(); }, 400);
    };
  </script>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (!win) {
    alert('Please allow popups to export PDF.');
    return;
  }
  win.document.write(html);
  win.document.close();
}