import React, { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import {
  ChevronRight, ChevronLeft, X, Zap, Volume2, SkipForward,
  CheckCircle2, AlertCircle, Lightbulb
} from 'lucide-react';
import { toast } from 'sonner';

const TUTORIAL_STEPS = [
  {
    id: 'welcome',
    title: 'Welcome to TeamSync',
    description: 'Simulate how your team would respond to key decisions before making them.',
    longContent: 'This tutorial will guide you through building your first simulation. We\'ll cover scenario setup, role selection, and running the analysis.',
    position: 'center',
    highlights: [],
    tips: [
      'Each simulation takes ~2-3 minutes to complete',
      'You can save drafts and return later',
      'Simulations are shareable with your team'
    ]
  },
  {
    id: 'scenario-focus',
    title: 'Describe Your Decision',
    description: 'The better your scenario, the better the simulation. Include context, constraints, and what\'s at stake.',
    longContent: 'Write 2-3 sentences describing a real decision your team faces. Include:\n• What needs to be decided\n• Key constraints (timeline, budget, people)\n• What success looks like\n• Any stakeholder perspectives you want to test',
    position: 'center',
    highlights: ['#scenario-input'],
    tips: [
      'More specific = better results',
      'Real scenarios work better than hypothetical ones',
      'You\'ll get real-time AI quality feedback'
    ]
  },
  {
    id: 'role-selection',
    title: 'Pick the Roles in the Room',
    description: 'Select 3-6 roles representing the voices that matter in this decision.',
    longContent: 'Think about who would actually be in the meeting:\n• Functional leaders (PM, Eng Lead, etc.)\n• Perspectives (data-driven vs risk-averse)\n• Stakeholders with veto power\n• Team members who would be affected',
    position: 'center',
    highlights: ['#role-grid'],
    tips: [
      'Diversity of perspectives creates richer tensions',
      'You can customize role personas for your team',
      'AI will suggest missing critical roles'
    ]
  },
  {
    id: 'composition-check',
    title: 'Team Composition Analysis',
    description: 'AI analyzes whether you\'ve got the right mix of voices for this decision.',
    longContent: 'This AI check will:\n• Score the composition (0-100)\n• Highlight missing critical voices\n• Predict the key tensions that will emerge\n• Recommend role adjustments',
    position: 'center',
    highlights: ['#composition-section'],
    tips: [
      'Listen to warnings about missing perspectives',
      'Balance is key - avoid echo chambers',
      'Recommended score: 70+/100'
    ]
  },
  {
    id: 'use-case-type',
    title: 'Classify the Decision Type',
    description: 'Choose the decision framework that best fits your scenario.',
    longContent: 'Different decisions benefit from different frameworks:\n• Pre-Mortem: Imagine failure before it happens\n• Roadmap: What to build next\n• ADR: Technical architecture choices\n• Post-Mortem: Learn from what went wrong',
    position: 'center',
    highlights: ['#use-case-grid'],
    tips: [
      'Not sure? Click "Suggest for my scenario"',
      'AI will analyze your scenario and recommend a type',
      'You can always change this later'
    ]
  },
  {
    id: 'review-launch',
    title: 'Ready to Run',
    description: 'Review your setup and launch the simulation. AI will generate responses for each role.',
    longContent: 'On the next screen:\n• Review your simulation title (auto-generated by AI)\n• Check your scenario and role selection\n• Hit "Run Simulation" to start the analysis\n• Results will include positions, tensions, and next steps',
    position: 'center',
    highlights: [],
    tips: [
      'First simulation usually takes 60-90 seconds',
      'You can re-run anytime to test changes',
      'Save results to compare alternatives'
    ]
  }
];

export default function InteractiveTutorial({ open, onClose, currentStep = 0 }) {
  const [activeStep, setActiveStep] = useState(currentStep);
  const [readMore, setReadMore] = useState(false);
  const [sound, setSound] = useState(true);

  const step = TUTORIAL_STEPS[activeStep];

  useEffect(() => {
    if (!open) return;
    const handleKey = (e) => {
      if (e.key === 'ArrowRight') moveNext();
      if (e.key === 'ArrowLeft') movePrev();
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleKey);
    return () => window.removeEventListener('keydown', handleKey);
  }, [activeStep, open]);

  const moveNext = () => {
    if (activeStep < TUTORIAL_STEPS.length - 1) {
      setActiveStep(activeStep + 1);
      setReadMore(false);
    } else {
      onClose();
    }
  };

  const movePrev = () => {
    if (activeStep > 0) {
      setActiveStep(activeStep - 1);
      setReadMore(false);
    }
  };

  const skipTutorial = () => {
    toast.info('Tutorial skipped. You can restart anytime from settings.');
    onClose();
  };

  if (!open) return null;

  const progress = ((activeStep + 1) / TUTORIAL_STEPS.length) * 100;

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl bg-white shadow-2xl">
        {/* Header with Step Indicator */}
        <div className="px-6 pt-6 pb-4 border-b border-slate-100">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 bg-gradient-to-br from-violet-600 to-violet-700 rounded-lg flex items-center justify-center shadow-lg">
                <Lightbulb className="w-5 h-5 text-white" />
              </div>
              <div>
                <h2 className="text-lg font-bold text-slate-900">{step.title}</h2>
                <p className="text-xs text-slate-500 mt-0.5">
                  Step {activeStep + 1} of {TUTORIAL_STEPS.length}
                </p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="text-slate-400 hover:text-slate-600 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Circular Step Indicator */}
          <div className="flex gap-2 items-center mb-3">
            {TUTORIAL_STEPS.map((s, i) => (
              <React.Fragment key={s.id}>
                <button
                  onClick={() => {
                    setActiveStep(i);
                    setReadMore(false);
                  }}
                  className={`
                    relative h-8 w-8 rounded-full font-semibold text-xs transition-all
                    ${
                      i === activeStep
                        ? 'bg-violet-600 text-white shadow-lg ring-4 ring-violet-200 scale-125'
                        : i < activeStep
                        ? 'bg-emerald-100 text-emerald-700 hover:bg-emerald-200'
                        : 'bg-slate-200 text-slate-600 hover:bg-slate-300'
                    }
                  `}
                  title={s.title}
                >
                  {i < activeStep ? (
                    <CheckCircle2 className="w-4 h-4" />
                  ) : (
                    i + 1
                  )}
                </button>
                {i < TUTORIAL_STEPS.length - 1 && (
                  <div
                    className={`flex-1 h-1 rounded-full ${
                      i < activeStep ? 'bg-emerald-200' : 'bg-slate-200'
                    }`}
                  />
                )}
              </React.Fragment>
            ))}
          </div>

          {/* Progress bar */}
          <div className="w-full bg-slate-200 rounded-full h-1.5 overflow-hidden">
            <div
              className="bg-gradient-to-r from-violet-600 to-violet-500 h-full transition-all duration-300"
              style={{ width: `${progress}%` }}
            />
          </div>
        </div>

        {/* Content */}
        <div className="px-6 py-5 space-y-4">
          {/* Description */}
          <div className="bg-gradient-to-br from-violet-50 to-blue-50 border border-violet-200 rounded-xl p-4">
            <p className="text-sm font-medium text-slate-800 leading-relaxed">
              {step.description}
            </p>
          </div>

          {/* Long Content */}
          <div className="space-y-2">
            {readMore && (
              <div className="bg-slate-50 border border-slate-200 rounded-lg p-4 space-y-2">
                <p className="text-sm text-slate-700 whitespace-pre-line leading-relaxed">
                  {step.longContent}
                </p>
              </div>
            )}
            <button
              onClick={() => setReadMore(!readMore)}
              className="text-xs text-violet-600 font-medium hover:text-violet-700 transition-colors flex items-center gap-1"
            >
              {readMore ? '← Hide details' : 'Show more details →'}
            </button>
          </div>

          {/* Tips */}
          {step.tips?.length > 0 && (
            <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 space-y-2">
              <p className="text-xs font-semibold text-amber-900 flex items-center gap-1.5">
                <AlertCircle className="w-3.5 h-3.5" /> Pro Tips
              </p>
              <ul className="space-y-1">
                {step.tips.map((tip, i) => (
                  <li key={i} className="text-xs text-amber-800 flex gap-2">
                    <span className="text-amber-600 font-bold mt-0.5">•</span>
                    <span>{tip}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-slate-100 bg-slate-50 flex items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <button
              onClick={() => setSound(!sound)}
              className={`p-1.5 rounded-lg transition-colors ${
                sound
                  ? 'bg-violet-100 text-violet-600'
                  : 'bg-slate-200 text-slate-600'
              }`}
              title={sound ? 'Mute' : 'Unmute'}
            >
              <Volume2 className="w-3.5 h-3.5" />
            </button>
            <button
              onClick={skipTutorial}
              className="text-xs text-slate-500 hover:text-slate-700 transition-colors flex items-center gap-1"
            >
              <SkipForward className="w-3 h-3" /> Skip tutorial
            </button>
          </div>

          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={movePrev}
              disabled={activeStep === 0}
              className="gap-1 h-8 text-xs"
            >
              <ChevronLeft className="w-3.5 h-3.5" /> Back
            </Button>
            <Button
              size="sm"
              onClick={moveNext}
              className="gap-1 h-8 text-xs bg-violet-600 hover:bg-violet-700"
            >
              {activeStep === TUTORIAL_STEPS.length - 1 ? 'Finish' : 'Next'}
              <ChevronRight className="w-3.5 h-3.5" />
            </Button>
          </div>
        </div>

        {/* Keyboard hint */}
        <div className="px-6 pb-3 text-center">
          <p className="text-xs text-slate-400">
            ← → arrow keys • ESC to close
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
}